---
# handlers file for install_nginx
- name: startup nginx
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: start nginx
  systemd:
    name: nginx
    state: started

- name: stop nginx
  systemd:
    name: nginx
    state: stopped

- name: restart nginx
  systemd:
    name: nginx
    state: restarted