# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"
  config.vm.box_version = "1804.2"

  config.vm.provider "virtualbox" do |v|
    v.memory = 256
    v.cpus = 1
    v.gui = true
  end

  config.vm.define "efi" do |efi|
    efi.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "net1"
    efi.vm.hostname = "nfss"
  end

end

