# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
    #ansible.verbose = "vvv"
    ansible.playbook = "playbook.yml"
    ansible.become = "true"
  end

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
  end

  config.vm.define "elk" do |elk|
    elk.vm.network "forwarded_port", guest: 80, host: 8080
    elk.vm.network "private_network", ip: "192.168.50.10", virtualbox__intnet: "dns"
    #config.vm.network "public_network", ip: "192.168.112.121"
    elk.vm.hostname = "elk"
  end

  config.vm.define "web" do |web|
    web.vm.network "forwarded_port", guest: 80, host: 9191
    web.vm.network "private_network", ip: "192.168.50.15", virtualbox__intnet: "dns"
    #config.vm.network "public_network", ip: "192.168.112.120"
    web.vm.hostname = "web"
  end

end
