# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
 config.vm.box = "centos/7"
 config.vm.define "server" do |server|
 #server.vm.hostname = "server.loc"
 server.vm.network "private_network", ip: "192.168.10.10"
 server.vm.hostname = "server"
 end
 
  config.vm.provision "ansible" do |ansible|
    #ansible.verbose = "vvv"
    #ansible.inventory_path = './playbooks/all.yml'
    ansible.playbook = "./provision/playbook.yml"
    ansible.become = "true"
  end

end