# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provider "virtualbox" do |v|
	  v.memory = 512
  end

  config.vm.provision "ansible" do |ansible|
    #ansible.verbose = "vvv"
    ansible.playbook = "playbook.yml"
    ansible.become = "true"
  end

  config.vm.define "nginx" do |nginx|
    config.vm.network "public_network", ip: "192.168.112.121"
    nginx.vm.hostname = "nginxserver"
  end
end
